export const tasksData = [
  {
    id: 1,
    description: "Задача 1",
    createdAt: new Date("2025-03-01"),
    deadline: new Date("2025-03-05"),
    participants: ["Иван", "Анна"],
    tags: ["Срочно", "Разработка"],
    isCompleted: false,
  },
  {
    id: 2,
    description: "Задача 2",
    createdAt: new Date("2025-02-28"),
    deadline: new Date("2025-03-04"),
    participants: ["Олег"],
    tags: ["Правки", "Мелкое"],
    isCompleted: false,
  },
  {
    id: 3,
    description: "Задача 3",
    createdAt: new Date("2025-02-27"),
    deadline: new Date("2025-03-10"),
    participants: ["Дмитрий", "Елена"],
    tags: ["Ожидает", "Тестирование"],
    isCompleted: false,
  },
  {
    id: 4,
    description: "Задача 4",
    createdAt: new Date("2025-02-20"),
    deadline: new Date("2025-03-01"),
    participants: ["Виктор", "Алексей"],
    tags: ["Не срочно", "Дизайн"],
    isCompleted: false,
  },
  {
    id: 5,
    description: "Задача 5",
    createdAt: new Date("2025-03-01"),
    deadline: new Date("2025-03-02"),
    participants: ["Анна", "Сергей"],
    tags: ["Тестирование", "Важное"],
    isCompleted: true,
  },
  {
    id: 6,
    description: "Задача 6",
    createdAt: new Date("2025-02-15"),
    deadline: new Date("2025-03-15"),
    participants: ["Ирина", "Светлана"],
    tags: ["Отложено", "Разработка"],
    isCompleted: false,
  },
  {
    id: 7,
    description: "Задача 7",
    createdAt: new Date("2025-02-10"),
    deadline: new Date("2025-03-07"),
    participants: ["Денис", "Алексей"],
    tags: ["Запуск", "Мелкое"],
    isCompleted: false,
  },
  {
    id: 8,
    description: "Задача 8",
    createdAt: new Date("2025-01-25"),
    deadline: new Date("2025-03-20"),
    participants: ["Марина", "Григорий"],
    tags: ["Планирование", "Важное"],
    isCompleted: false,
  },
  {
    id: 9,
    description: "Задача 9",
    createdAt: new Date("2025-01-30"),
    deadline: new Date("2025-03-09"),
    participants: ["Роман", "Ольга"],
    tags: ["Документация"],
    isCompleted: false,
  },
  {
    id: 10,
    description: "Задача 10",
    createdAt: new Date("2025-02-18"),
    deadline: new Date("2025-03-14"),
    participants: ["Андрей", "Ирина"],
    tags: ["Безопасность", "Срочно"],
    isCompleted: true,
  },
];
